codecov:
  require_ci_to_pass: true
  strict_yaml_branch: master

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 3%
    patch:
      default:
        target: 80%
        threshold: 0%

ignore:
  - "apps/**"
  - "build/**"
  - "install/**"
  - "test/**"
