message(STATUS "====================================================================================================")
message(STATUS "${PROJECT_NAME} ${PROJECT_VERSION} CONFIGURATION SUMMARY")
message(STATUS "====================================================================================================")
message(STATUS "CMAKE_CXX_COMPILER: ${CMAKE_CXX_COMPILER}")
message(STATUS "CMAKE_C_COMPILER: ${CMAKE_C_COMPILER}")
message(STATUS "CMAKE_MAKE_PROGRAM: ${CMAKE_MAKE_PROGRAM}")
message(STATUS "CMAKE_LINKER: ${CMAKE_LINKER}")
message(STATUS "----------------------------------------------------------------------------------------------------")
message(STATUS "CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")
message(STATUS "CMAKE_CXX_EXTENSIONS: ${CMAKE_CXX_EXTENSIONS}")
message(STATUS "----------------------------------------------------------------------------------------------------")
message(STATUS "BUILD_DOCS: ${BUILD_DOCS}")
message(STATUS "BUILD_TESTING: ${BUILD_TESTING}")
message(STATUS "ENABLE_COVERAGE: ${ENABLE_COVERAGE}")
message(STATUS "----------------------------------------------------------------------------------------------------")
message(STATUS "BOLT_ARCHITECTURE_FLAGS: ${BOLT_ARCHITECTURE_FLAGS}")
message(STATUS "LOG_LEVEL: ${LOG_LEVEL}")
message(STATUS "USE_SYSTEM_CATCH2: ${USE_SYSTEM_CATCH2}")
message(STATUS "USE_SYSTEM_CLI11: ${USE_SYSTEM_CLI11}")
message(STATUS "USE_SYSTEM_QUILL: ${USE_SYSTEM_QUILL}")
message(STATUS "USE_SYSTEM_TOMLPLUSPLUS: ${USE_SYSTEM_TOMLPLUSPLUS}")
message(STATUS "----------------------------------------------------------------------------------------------------")
message(STATUS "Catch2_DIR: ${Catch2_DIR}")
message(STATUS "CLI11_DIR: ${CLI11_DIR}")
message(STATUS "quill_DIR: ${quill_DIR}")
message(STATUS "tomlplusplus_DIR: ${tomlplusplus_DIR}")
message(STATUS "====================================================================================================")
