message(STATUS "====================================================================================================")
message(STATUS "CMAKE CONFIGURATION FOR ${PROJECT_NAME} ${PROJECT_VERSION}")
message(STATUS "====================================================================================================")
message(STATUS "CMAKE_CXX_COMPILER: ${CMAKE_CXX_COMPILER}")
message(STATUS "CMAKE_C_COMPILER: ${CMAKE_C_COMPILER}")
message(STATUS "CMAKE_GENERATOR: ${CMAKE_GENERATOR}")
message(STATUS "CMAKE_LINKER: ${CMAKE_LINKER}")
message(STATUS "----------------------------------------------------------------------------------------------------")
message(STATUS "BOLT_ARCHITECTURE_FLAGS: ${BOLT_ARCHITECTURE_FLAGS}")
message(STATUS "CMAKE_CXX_EXTENSIONS: ${CMAKE_CXX_EXTENSIONS}")
message(STATUS "CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")
message(STATUS "----------------------------------------------------------------------------------------------------")
message(STATUS "BUILD_DOCS: ${BUILD_DOCS}")
message(STATUS "BUILD_TESTING: ${BUILD_TESTING}")
message(STATUS "CMAKE_EXPORT_COMPILE_COMMANDS: ${CMAKE_EXPORT_COMPILE_COMMANDS}")
message(STATUS "ENABLE_COVERAGE: ${ENABLE_COVERAGE}")
message(STATUS "====================================================================================================")
