name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-26.04
    container:
      image: ghcr.io/cfbaptista/bolt-dev:0.4.0-amd64

    steps:
      - name: Fix dubious ownership warning
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run formatter (clang-format)
        run: |
          clang-format \
            --style=file \
            $(git ls-files '*.cpp' '*.hpp' '*.tpp') \
            --dry-run \
            --Werror \
            2>&1

  build-test:
    needs: format
    name: ${{ matrix.arch }} / ${{ matrix.toolchain }} / ${{ matrix.build_type }}
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.container }}
    env:
      PRESET: linux-native-${{ matrix.toolchain }}-${{ matrix.build_type }}
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        toolchain:
          - gnu
          - llvm
        build_type:
          - debug
          - release
        include:
          - arch: x86_64
            runner: ubuntu-26.04
            container: ghcr.io/cfbaptista/bolt-dev:0.4.0-amd64
          - arch: aarch64
            runner: ubuntu-26.04-arm
            container: ghcr.io/cfbaptista/bolt-dev:0.4.0-arm64
      fail-fast: false

    steps:
      - name: Fix dubious ownership warning
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Show architecture
        run: uname -m

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure project
        run: cmake --preset ${{ env.PRESET }} -DBUILD_DOCS=OFF -DBUILD_TESTING=ON

      - name: Run fast static analysis (cppcheck)
        run: |
          cppcheck \
            --project=build/${{ env.PRESET }}/compile_commands.json \
            --enable=all \
            --inconclusive \
            --force \
            --check-level=exhaustive \
            --suppress=missingIncludeSystem \
            --inline-suppr \
            --std=c++23 \
            --error-exitcode=1 \
            -i build/${{ env.PRESET }}/_deps
            2>&1

      - name: Build project
        run: cmake --build --preset ${{ env.PRESET }}

      - name: Run comprehensive static analysis (clang-tidy)
        if: contains(env.PRESET, 'llvm')
        run: |
          clang-tidy \
            $(git ls-files '*.cpp') \
            -p build/${{ env.PRESET }} \
            2>&1

      - name: Test project
        run: ctest --preset ${{ env.PRESET }}

      - name: Install project
        run: cmake --install build/${{ env.PRESET }} --prefix install/${{ env.PRESET }}

  documentation:
    needs: build-test
    name: Build documentation
    runs-on: ubuntu-26.04
    container:
      image: ghcr.io/cfbaptista/bolt-dev:0.4.0-amd64

    steps:
      - name: Fix dubious ownership warning
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure project
        run: cmake --preset linux-native-llvm-release -DBUILD_DOCS=ON -DBUILD_TESTING=OFF

      - name: Run documentation generator (Doxygen)
        run: cmake --build --preset linux-native-llvm-release --target docs

  coverage:
    needs: build-test
    name: Report code coverage
    runs-on: ubuntu-26.04
    container:
      image: ghcr.io/cfbaptista/bolt-dev:0.4.0-amd64

    steps:
      - name: Fix dubious ownership warning
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure project
        run: cmake --preset linux-native-llvm-debug -DBUILD_DOCS=OFF -DBUILD_TESTING=ON -DENABLE_COVERAGE=ON

      - name: Build project
        run: cmake --build --preset linux-native-llvm-debug

      - name: Generate coverage report
        run: cmake --build --preset linux-native-llvm-debug --target coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/linux-native-llvm-debug/coverage/llvm/coverage.lcov
          fail_ci_if_error: true

  success:
    needs:
      - format
      - build-test
      - documentation
      - coverage
    name: Success
    runs-on: ubuntu-26.04

    steps:
      - name: Report success
        run: echo "All checks passed successfully!"
